'use strict';

/**
 * Auto-generated Mock Server
 * Source contract: mock-server-test.yaml (Task Manager API v1.0.0)
 * Generated by the `create-mock-server` skill.
 *
 * Implements:
 *   - Users CRUD:  GET/POST /users, GET/PUT/DELETE /users/{userId}
 *   - Tasks CRUD:  GET/POST /tasks, GET/PATCH/DELETE /tasks/{taskId}
 *   - Mock control params: _delay / X-Mock-Delay, _status / X-Mock-Status
 *   - GET /_health
 *
 * Assumption (documented per skill constraints): the contract declares
 * `bearerAuth` security and 401 responses on every operation, but defines
 * no login/token endpoint. Since there is nothing to validate a token
 * against, authentication is NOT enforced by default so the mock stays
 * usable out of the box. 401 responses can still be exercised explicitly
 * via `_status=401` (or `X-Mock-Status: 401`) on any request.
 */

const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 8080;

// ---------------------------------------------------------------------------
// Dynamic data helpers (no static hardcoded payloads)
// ---------------------------------------------------------------------------

const FIRST_NAMES = ['Jane', 'John', 'Emily', 'Michael', 'Sara', 'David', 'Anna', 'Chris', 'Laura', 'Tom'];
const LAST_NAMES = ['Doe', 'Smith', 'Johnson', 'Brown', 'Taylor', 'Anderson', 'Clark', 'Lewis', 'Walker', 'Young'];
const ROLES = ['admin', 'member', 'viewer'];
const TASK_STATUSES = ['todo', 'in_progress', 'blocked', 'done'];
const PRIORITIES = ['low', 'medium', 'high', 'critical'];
const TASK_TITLES = [
  'Prepare Q3 roadmap presentation',
  'Fix login page validation bug',
  'Write onboarding documentation',
  'Review pull request for payments module',
  'Set up CI pipeline for mobile app',
  'Design new dashboard widgets',
  'Investigate production latency spike',
  'Migrate database to new schema',
  'Update API documentation',
  'Conduct sprint retrospective'
];
const TAG_POOL = ['roadmap', 'q3', 'bug', 'frontend', 'backend', 'docs', 'onboarding', 'urgent', 'infra', 'design'];

function randomUUID() {
  return crypto.randomUUID();
}

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function pickSome(arr, min = 1, max = 3) {
  const count = Math.floor(Math.random() * (max - min + 1)) + min;
  const shuffled = [...arr].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randomPastISODate(maxDaysAgo = 180) {
  const d = new Date(Date.now() - randomInt(0, maxDaysAgo) * 24 * 60 * 60 * 1000);
  return d.toISOString();
}

function randomFutureDateOnly(maxDaysAhead = 90) {
  const d = new Date(Date.now() + randomInt(1, maxDaysAhead) * 24 * 60 * 60 * 1000);
  return d.toISOString().split('T')[0];
}

function randomUsername(first, last) {
  return `${first.toLowerCase()}.${last.toLowerCase()}`;
}

function generateUser() {
  const first = pick(FIRST_NAMES);
  const last = pick(LAST_NAMES);
  const username = randomUsername(first, last);
  const createdAt = randomPastISODate(180);
  return {
    id: randomUUID(),
    email: `${username}@example.com`,
    username,
    fullName: `${first} ${last}`,
    role: pick(ROLES),
    isActive: Math.random() > 0.15,
    createdAt,
    updatedAt: createdAt
  };
}

function generateTask(userIds) {
  const createdAt = randomPastISODate(120);
  return {
    id: randomUUID(),
    title: pick(TASK_TITLES),
    description: 'Auto-generated mock task description for testing purposes.',
    status: pick(TASK_STATUSES),
    priority: pick(PRIORITIES),
    assigneeId: userIds.length && Math.random() > 0.1 ? pick(userIds) : null,
    dueDate: Math.random() > 0.2 ? randomFutureDateOnly() : null,
    tags: pickSome(TAG_POOL, 1, 3),
    createdAt,
    updatedAt: createdAt
  };
}

function makeError(status, message, details) {
  const payload = {
    error: true,
    status,
    message,
    timestamp: new Date().toISOString()
  };
  if (details) payload.details = details;
  return payload;
}

// ---------------------------------------------------------------------------
// In-memory seeded datastore (3-10 items per collection, per mock-rules.md)
// ---------------------------------------------------------------------------

let users = Array.from({ length: randomInt(3, 10) }, generateUser);
let tasks = Array.from({ length: randomInt(3, 10) }, () => generateTask(users.map((u) => u.id)));

// ---------------------------------------------------------------------------
// Global middleware
// ---------------------------------------------------------------------------

app.use(cors());
app.use(bodyParser.json());

// Malformed JSON body handling -> 400 Bad Request
app.use((err, req, res, next) => {
  if (err && err.type === 'entity.parse.failed') {
    return res.status(400).json(makeError(400, 'Malformed JSON in request body'));
  }
  next(err);
});

// Request logging middleware
app.use((req, res, next) => {
  const start = Date.now();
  res.on('finish', () => {
    console.log(`[${new Date().toISOString()}] ${req.method} ${req.originalUrl} -> ${res.statusCode} (${Date.now() - start}ms)`);
  });
  next();
});

// Mock delay simulation: `_delay` query param or `X-Mock-Delay` header (ms)
app.use((req, res, next) => {
  const delay = parseInt(req.query._delay || req.headers['x-mock-delay'] || 0, 10);
  if (delay > 0) {
    setTimeout(next, delay);
  } else {
    next();
  }
});

// Mock error simulation: `_status` query param or `X-Mock-Status` header
app.use((req, res, next) => {
  const statusOverride = parseInt(req.query._status || req.headers['x-mock-status'] || 0, 10);
  if (statusOverride >= 400 && statusOverride < 600) {
    return res.status(statusOverride).json(
      makeError(statusOverride, `Simulated Mock Error for status code ${statusOverride}`)
    );
  }
  next();
});

// ---------------------------------------------------------------------------
// Health check
// ---------------------------------------------------------------------------

app.get('/_health', (req, res) => {
  res.status(200).json({
    status: 'ok',
    uptimeSeconds: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

// ---------------------------------------------------------------------------
// Shared pagination helper
// ---------------------------------------------------------------------------

function paginate(items, req) {
  const page = Math.max(parseInt(req.query.page, 10) || 1, 1);
  const limit = Math.min(Math.max(parseInt(req.query.limit, 10) || 10, 1), 100);
  const total = items.length;
  const totalPages = Math.max(Math.ceil(total / limit), 1);
  const start = (page - 1) * limit;
  const data = items.slice(start, start + limit);
  return { data, pagination: { page, limit, total, totalPages } };
}

// ---------------------------------------------------------------------------
// Users routes
// ---------------------------------------------------------------------------

app.get('/users', (req, res) => {
  const { data, pagination } = paginate(users, req);
  res.status(200).json({ data, pagination });
});

app.post('/users', (req, res) => {
  const body = req.body || {};
  const details = [];

  if (!body.email || !/^\S+@\S+\.\S+$/.test(body.email)) {
    details.push({ field: 'email', message: 'must be a valid email address' });
  }
  if (!body.username || String(body.username).length < 3 || String(body.username).length > 32) {
    details.push({ field: 'username', message: 'is required and must be 3-32 characters long' });
  }
  if (!body.password || String(body.password).length < 8) {
    details.push({ field: 'password', message: 'is required and must be at least 8 characters long' });
  }

  if (details.length > 0) {
    return res.status(400).json(makeError(400, 'Validation failed for one or more fields', details));
  }

  const now = new Date().toISOString();
  const newUser = {
    id: randomUUID(),
    email: body.email,
    username: body.username,
    fullName: body.fullName || '',
    role: ROLES.includes(body.role) ? body.role : 'member',
    isActive: true,
    createdAt: now,
    updatedAt: now
  };
  users.push(newUser);
  res.status(201).json(newUser);
});

app.get('/users/:userId', (req, res) => {
  const user = users.find((u) => u.id === req.params.userId);
  if (!user) {
    return res.status(404).json(makeError(404, `User ${req.params.userId} not found`));
  }
  res.status(200).json(user);
});

app.put('/users/:userId', (req, res) => {
  const user = users.find((u) => u.id === req.params.userId);
  if (!user) {
    return res.status(404).json(makeError(404, `User ${req.params.userId} not found`));
  }
  const body = req.body || {};
  if (body.role !== undefined && !ROLES.includes(body.role)) {
    return res.status(400).json(
      makeError(400, 'Validation failed for one or more fields', [
        { field: 'role', message: `must be one of: ${ROLES.join(', ')}` }
      ])
    );
  }
  if (body.fullName !== undefined) user.fullName = body.fullName;
  if (body.role !== undefined) user.role = body.role;
  if (body.isActive !== undefined) user.isActive = Boolean(body.isActive);
  user.updatedAt = new Date().toISOString();
  res.status(200).json(user);
});

app.delete('/users/:userId', (req, res) => {
  const index = users.findIndex((u) => u.id === req.params.userId);
  if (index === -1) {
    return res.status(404).json(makeError(404, `User ${req.params.userId} not found`));
  }
  users.splice(index, 1);
  res.status(204).send();
});

// ---------------------------------------------------------------------------
// Tasks routes
// ---------------------------------------------------------------------------

app.get('/tasks', (req, res) => {
  let filtered = tasks;
  if (req.query.status) {
    filtered = filtered.filter((t) => t.status === req.query.status);
  }
  if (req.query.assigneeId) {
    filtered = filtered.filter((t) => t.assigneeId === req.query.assigneeId);
  }
  const { data, pagination } = paginate(filtered, req);
  res.status(200).json({ data, pagination });
});

app.post('/tasks', (req, res) => {
  const body = req.body || {};
  if (!body.title || String(body.title).trim().length === 0) {
    return res.status(400).json(
      makeError(400, 'Validation failed for one or more fields', [
        { field: 'title', message: 'is required' }
      ])
    );
  }

  const now = new Date().toISOString();
  const newTask = {
    id: randomUUID(),
    title: body.title,
    description: body.description || '',
    status: 'todo',
    priority: PRIORITIES.includes(body.priority) ? body.priority : 'medium',
    assigneeId: body.assigneeId || null,
    dueDate: body.dueDate || null,
    tags: Array.isArray(body.tags) ? body.tags : [],
    createdAt: now,
    updatedAt: now
  };
  tasks.push(newTask);
  res.status(201).json(newTask);
});

app.get('/tasks/:taskId', (req, res) => {
  const task = tasks.find((t) => t.id === req.params.taskId);
  if (!task) {
    return res.status(404).json(makeError(404, `Task ${req.params.taskId} not found`));
  }
  res.status(200).json(task);
});

app.patch('/tasks/:taskId', (req, res) => {
  const task = tasks.find((t) => t.id === req.params.taskId);
  if (!task) {
    return res.status(404).json(makeError(404, `Task ${req.params.taskId} not found`));
  }
  const body = req.body || {};

  if (body.status !== undefined && !TASK_STATUSES.includes(body.status)) {
    return res.status(400).json(
      makeError(400, 'Validation failed for one or more fields', [
        { field: 'status', message: `must be one of: ${TASK_STATUSES.join(', ')}` }
      ])
    );
  }
  if (body.priority !== undefined && !PRIORITIES.includes(body.priority)) {
    return res.status(400).json(
      makeError(400, 'Validation failed for one or more fields', [
        { field: 'priority', message: `must be one of: ${PRIORITIES.join(', ')}` }
      ])
    );
  }

  if (body.title !== undefined) task.title = body.title;
  if (body.description !== undefined) task.description = body.description;
  if (body.status !== undefined) task.status = body.status;
  if (body.priority !== undefined) task.priority = body.priority;
  if (body.assigneeId !== undefined) task.assigneeId = body.assigneeId;
  if (body.dueDate !== undefined) task.dueDate = body.dueDate;
  if (body.tags !== undefined) task.tags = body.tags;
  task.updatedAt = new Date().toISOString();

  res.status(200).json(task);
});

app.delete('/tasks/:taskId', (req, res) => {
  const index = tasks.findIndex((t) => t.id === req.params.taskId);
  if (index === -1) {
    return res.status(404).json(makeError(404, `Task ${req.params.taskId} not found`));
  }
  tasks.splice(index, 1);
  res.status(204).send();
});

// ---------------------------------------------------------------------------
// Fallback 404 for unknown routes + generic error handler
// ---------------------------------------------------------------------------

app.use((req, res) => {
  res.status(404).json(makeError(404, `Route ${req.method} ${req.originalUrl} not found`));
});

// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  console.error('Unhandled error:', err);
  res.status(500).json(makeError(500, 'Unexpected server-side error'));
});

app.listen(PORT, () => {
  console.log(`Mock server (Task Manager API) listening on port ${PORT}`);
  console.log(`Seeded ${users.length} users and ${tasks.length} tasks`);
  console.log(`Health check: http://localhost:${PORT}/_health`);
});
